- name: Instalar Aplicativo no Dispositivo
      run: |
        echo "Extraindo informações da reserva..."
        DEVICE_ID=$(jq -r '.device.id' response.json)

        # Se o ID da reserva for nulo, usa o chumbado como fallback
        if [ "$DEVICE_ID" == "null" ] || [ -z "$DEVICE_ID" ]; then
          DEVICE_ID="00008030-00040D410247802E"
          echo "Usando ID chumbado: $DEVICE_ID"
        else
          echo "Dispositivo reservado: $DEVICE_ID"
        fi

        echo "Extraindo ID do aplicativo enviado..."
        APP_UUID=$(jq -r '.uuid' upload_response.json)
        APP_ID=$(jq -r '.id' upload_response.json)
        APP_COUNTER=$(jq -r '.counter' upload_response.json)

        echo "Aplicativo enviado: $APP_ID $APP_COUNTER $APP_UUID"

        echo "Instalando aplicativo no UFT Mobile..."
        RESPONSE=$(curl -k -s -X POST "https://labmobile.keeggo.com/rest/apps/install" \
          -H "Authorization: Bearer ${{ env.TOKEN }}" \
          -H "x-hp4msecret: ${{ env.X_HP4MSECRET }}" \
          -H "Content-Type: application/json" \
          -d "{
                \"app\": {
                  \"id\": \"$APP_ID\",
                  \"uuid\": \"$APP_UUID\",
                  \"instrumented\": true,
                  \"counter\": $APP_COUNTER
                },
                \"deviceCapabilities\": {
                  \"udid\": \"$DEVICE_ID\"
                }
              }")

        echo "Resposta da instalação:"
        echo "$RESPONSE"

   

