name: Retrieve Token, Reserve Device and Upload Artefact

on:
  workflow_dispatch:
    inputs:
      artefact_url:
        description: 'URL do artefato a ser baixado'
        required: true

      id_device:
        description: 'ID do device'
        required: true

jobs:
  upload-application:
    runs-on: ubuntu-latest

    steps:
    - name: Install jq and unzip
      run: sudo apt-get install -y jq unzip

    - name: Calculate Start and End Times
      run: |
        echo "Calculando horários..."
        START_TIME=$(TZ=America/Sao_Paulo date +"%Y-%m-%dT%H:%M:%S%:z" -d "+1 minute")
        END_TIME=$(TZ=America/Sao_Paulo date +"%Y-%m-%dT%H:%M:%S%:z" -d "+1 hour 1 minute")

        echo "START_TIME=$START_TIME" >> $GITHUB_ENV
        echo "END_TIME=$END_TIME" >> $GITHUB_ENV

    - name: Generate OAuth Token
      env:
        CLIENT: ${{ secrets.CLIENT }}
        SECRET: ${{ secrets.SECRET }}
        TENANT: ${{ secrets.TENANT }}
      run: |
        echo "Gerando o token OAuth..."
        RESPONSE=$(curl -i -s -k -X POST https://labmobile.keeggo.com/rest/oauth2/token \
          -H "Content-Type: application/json" \
          -d "{\"client\":\"$CLIENT\", \"secret\":\"$SECRET\", \"tenant\":\"$TENANT\"}")

        HEADER_X_HP4MSECRET=$(echo "$RESPONSE" | grep -i "x-hp4msecret" | awk '{print $2}' | tr -d '\r')
        if [ -z "$HEADER_X_HP4MSECRET" ]; then
          echo "Erro: Cabeçalho x-hp4msecret não encontrado."
          exit 1
        fi

        TOKEN=$(echo "$RESPONSE" | awk 'BEGIN {RS=""; FS="\r\n\r\n"} {print $2}' | jq -r '.access_token')

        echo "TOKEN=$TOKEN" >> $GITHUB_ENV
        echo "X_HP4MSECRET=$HEADER_X_HP4MSECRET" >> $GITHUB_ENV

    - name: Busca de Device
      run: | 
        RESPONSE=$(curl -k -s -X GET "https://labmobile.keeggo.com/rest/deviceContent" \
          -H "Authorization: Bearer $TOKEN" \
          -H "x-hp4msecret: $X_HP4MSECRET" \
          -H "Content-Type: application/json")

        echo "$RESPONSE" > devices.json
    
        echo "Lista de UDIDs conectados e livres:"
        jq -r '.[] | select(.connected == true and .currentReservation.status == "Free") | .udid' devices.json
        jq . devices.json

    - name: Download Artefato
      run: |
        echo "Baixando o artefato..."
        ARTEFATO_NOME=$(basename "${{ github.event.inputs.artefact_url }}")
        curl -L -o "$ARTEFATO_NOME" "${{ github.event.inputs.artefact_url }}"

        if [ ! -f "$ARTEFATO_NOME" ]; then
          echo "Erro: Falha no download do artefato."
          exit 1
        fi
        echo "ARTEFATO_NOME=$ARTEFATO_NOME" >> $GITHUB_ENV

    - name: Verificar Artefato
      run: |
        EXTENSAO="${ARTEFATO_NOME##*.}"
        if [[ "$EXTENSAO" == "apk" ]]; then
          if ! unzip -l "$ARTEFATO_NOME" | grep -q AndroidManifest.xml; then
            echo "Erro: APK inválido."
            exit 1
          fi
        elif [[ "$EXTENSAO" == "ipa" ]]; then
          unzip -q "$ARTEFATO_NOME" -d extracted
          if [ ! -f extracted/Payload/*.app/Info.plist ]; then
            echo "Erro: IPA inválido."
            exit 1
          fi
        else
          echo "Erro: Extensão de arquivo não suportada."
          exit 1
        fi

    - name: Enviar Artefato para UFT Mobile
      run: |
        RESPONSE=$(curl -k -s -o upload_response.json -w "%{http_code}" -X POST https://labmobile.keeggo.com/rest/apps \
          -H "Authorization: Bearer $TOKEN" \
          -H "x-hp4msecret: $X_HP4MSECRET" \
          -F "file=@$ARTEFATO_NOME" \
          -F "fileName=$ARTEFATO_NOME" \
          -F "description=Aplicativo para teste" \
          -F "overrideExistingFile=true" \
          -F "package=false" \
          -F "workspaceId=de896153-bda6-4e11-a197-aa99b4a1f75e")

        HTTP_CODE=$(tail -n 1 <<< "$RESPONSE")
        if [ "$HTTP_CODE" -ne 200 ]; then
          echo "Erro no upload do artefato."
          cat upload_response.json
          exit 1
        fi
    - name: Instalar Aplicativo no Dispositivo
      run: |
    
        # Verificar ou determinar o DEVICE_ID
        if [ -z "$DEVICE_ID" ]; then
          echo "DEVICE_ID não informado. Selecionando automaticamente com base na extensão do app..."
    
          EXT="${ARTEFATO_NOME##*.}"
    
          if [[ "$EXT" == "ipa" ]]; then
            PLATAFORMA="iOS"
          elif [[ "$EXT" == "apk" ]]; then
            PLATAFORMA="Android"
          else
            echo "Extensão desconhecida: $EXT"
            exit 1
          fi
    
          # Buscar primeiro device disponível da plataforma
          DEVICE_ID=$(jq -r --arg plataforma "$PLATAFORMA" '
            .[] | select(
              .connected == true and 
              .currentReservation.status == "Free" and 
              .platformName == $plataforma
            ) | .udid' devices.json | head -n 1)
    
          if [ -z "$DEVICE_ID" ]; then
            echo "Nenhum device disponível para a plataforma $PLATAFORMA"
            exit 1
          fi
    
          DEVICE_NOME=$(jq -r --arg udid "$DEVICE_ID" '.[] | select(.udid == $udid) | .deviceName' devices.json)
          echo "Dispositivo selecionado automaticamente: $DEVICE_NOME ($DEVICE_ID)"
          echo "DEVICE_ID=$DEVICE_ID" >> $GITHUB_ENV
        else
          echo "DEVICE_ID informado manualmente: $DEVICE_ID"
          echo "DEVICE_ID=$DEVICE_ID" >> $GITHUB_ENV
        fi
    
        # Coletar dados do app
        APP_ID=$(jq -r '.id' upload_response.json)
        APP_UUID=$(jq -r '.uuid' upload_response.json)
        APP_COUNTER=$(jq -r '.counter' upload_response.json)
    
        # Enviar requisição de instalação
        RESPONSE=$(curl -k -s -X POST "https://labmobile.keeggo.com/rest/apps/install" \
          -H "Authorization: Bearer $TOKEN" \
          -H "x-hp4msecret: $X_HP4MSECRET" \
          -H "Content-Type: application/json" \
          -d "{
                \"app\": {
                  \"id\": \"$APP_UUID\",
                  \"uuid\": \"$APP_UUID\",
                  \"instrumented\": true
                },
                \"deviceCapabilities\": {
                  \"udid\": \"$DEVICE_ID\"
                }
              }")
    
        echo "Resposta da instalação:"
        echo "$RESPONSE"
              
    
    
