name: Generate Token and Use It

on:
  workflow_dispatch: # Permite execução manual do workflow

jobs:
  generate-token:
    runs-on: ubuntu-latest

    steps:
    - name: Generate OAuth Token
      env:
        CLIENT: ${{ vars.CLIENT }}
        SECRET: ${{ vars.SECRET }}
        TENANT: ${{ vars.TENANT }}
      run: |
        echo "Generating token with the following details:"
        echo "CLIENT: $CLIENT"
        echo "SECRET: $SECRET"
        echo "TENANT: $TENANT"
        curl -k -X POST https://labmobile.keeggo.com/rest/oauth2/token \
          -H "Content-Type: application/json" \
          -d '{
                "client": "'$CLIENT'",
                "secret": "'$SECRET'",
                "tenant": "'$TENANT'"
              }'
